Add section on wallets / clients
w3c/vc-jose-cose pull request #137
Opened 2023-08-15 15:32 UTC by OR13

Purpose of this PR is to provide informative context related to the "software system used by holders"... We have a number of core data model concepts that are tied to "holder" that are awkward to discuss without some ability to speak to the relationship between "wallets and holders".

2023-08-15 19:35 UTC, TallTed requested changes

2023-08-15 19:35 UTC, TallTed commented on index.html
> +  such clients are often referred to as wallets or digital credential wallets,
```suggestion
  as defined in <a href="https://datatracker.ietf.org/doc/html/rfc4949">RFC4949</a>.
  Such clients are often referred to as <i>wallets</i> or <i>digital credential wallets</i>,
```

2023-08-15 19:35 UTC, TallTed commented on index.html
> +  <a data-cite="VC-DATA-MODEL#dfn-holders">holder</a> prior to issuing and delivery credentials to a <a data-cite="VC-DATA-MODEL#dfn-holders">holder</a>.
```suggestion
  <a data-cite="VC-DATA-MODEL#dfn-issuers">issuers</a> might need to assess the quality of a wallet used by a 
  <a data-cite="VC-DATA-MODEL#dfn-holders">holder</a>, prior to issuing and
  delivering credentials to a <a data-cite="VC-DATA-MODEL#dfn-holders">holder</a>.
```

2023-08-15 19:35 UTC, TallTed commented on index.html
> +    See <a href="https://datatracker.ietf.org/doc/draft-looker-oauth-attestation-based-client-auth/">
```suggestion
    Also see <a href="https://datatracker.ietf.org/doc/draft-looker-oauth-attestation-based-client-auth/">
```

2023-08-16 13:19 UTC, OR13 commented
@TallTed thanks for the review!

2023-08-16 17:17 UTC, TallTed approved these changes

2023-08-17 19:03 UTC, brentzundel approved these changes

2023-08-23 20:03 UTC, merged