Update examples
w3c/vc-jose-cose pull request #139
Opened 2023-08-16 16:52 UTC by OR13

This PR updates the plugin and examples to use the latest approach to distinguishing content by media types.

2023-08-16 17:17 UTC, andresuribe87 approved these changes
This is 🔥

2023-08-16 17:23 UTC, TallTed requested changes

2023-08-16 17:23 UTC, TallTed commented on index.html
> +      <pre class="example vc-jose-cose-vc-example" title="A revocable credential withmultiple subjects" data-alg="ES256" data-typ="vc+ld+json+jwt" data-cty="vc+ld+json">
```suggestion
      <pre class="example vc-jose-cose-vc-example" title="A revocable credential with multiple subjects" data-alg="ES256" data-typ="vc+ld+json+jwt" data-cty="vc+ld+json">
```

2023-08-17 19:01 UTC, brentzundel approved these changes

2023-08-24 21:53 UTC, merged

2023-08-24 21:54 UTC, OR13 commented
ugh.... accidentally push this to main... granted it only updates the broken examples, which is editorial.