clarify that what is secured is a document conforming to vcdm
w3c/vc-jose-cose pull request #147
Opened 2023-09-07 20:30 UTC by Sakurann

for clarity. removing media types in the spirit of #143 (should probably be merged after that one, if ever.)
somewhat related to #15.

2023-09-08 00:09 UTC, OR13 approved these changes

2023-09-08 08:26 UTC, TallTed requested changes

2023-09-08 08:26 UTC, TallTed commented on index.html
> +          to the [[VC-DATA-MODEL]].
```suggestion
          This section details how to use JOSE to secure verifiable credentials conforming
          to the [[VC-DATA-MODEL]].
```

2023-09-08 08:26 UTC, TallTed commented on index.html
> +          to the [[VC-DATA-MODEL]].
```suggestion
          This section details how to use JOSE to secure verifiable presentations conforming
          to the [[VC-DATA-MODEL]].
```

2023-09-08 19:48 UTC, selfissued approved these changes

2023-09-11 09:30 UTC, brentzundel approved these changes

2023-09-11 16:50 UTC, TallTed requested changes
changes noted above

2023-09-12 17:07 UTC, Sakurann commented
all of Ted's proposed changes accepted :)

2023-09-13 13:49 UTC, merged