point to an ietf cose wg adopted draft for a COE typ header
w3c/vc-jose-cose pull request #152
Opened 2023-09-09 00:44 UTC by Sakurann

Issue #67

2023-09-09 01:09 UTC, cghost420 approved these changes

2023-09-10 03:58 UTC, cghost420 approved these changes

2023-09-11 09:43 UTC, brentzundel approved these changes

2023-09-11 09:58 UTC, selfissued approved these changes
LGTM

2023-09-11 15:52 UTC, OR13 approved these changes

2023-09-11 17:22 UTC, TallTed requested changes

2023-09-11 17:22 UTC, TallTed commented on index.html
> +          for COSE "typ" (type) header parameter.
```suggestion
          for the COSE "<code>typ</code>" (type) header parameter.
```

2023-09-12 17:18 UTC, Sakurann commented
@TallTed's suggestions approved.

2023-09-12 17:19 UTC, merged