Remove cross origin script
w3c/vc-jose-cose pull request #162
Opened 2023-10-02 20:39 UTC by OR13

This PR removes a cross origin script and improves the respec plugin used to process spec examples

It is editorial.

2023-10-04 17:03 UTC, decentralgabe approved these changes

2023-10-06 19:37 UTC, selfissued requested changes
Please delete the `proof` clauses, per my individual review comments.

2023-10-06 19:37 UTC, selfissued commented on index.html
> +    "proofValue": "zQeVbY4oey5q2M3XKaxup3tmzN4DRFTLVqpLMweBrSxMY2xHX5XTYV8nQApmEcqaqA3Q1gVHMrXFkXJeV6doDwLWx"
@OR13 please remove the `proof` section, as it uses a different securing mechanism than the one we're specifying.
```suggestion
```

2023-10-06 19:37 UTC, selfissued commented on index.html
> +      "proofValue": "zQeVbY4oey5q2M3XKaxup3tmzN4DRFTLVqpLMweBrSxMY2xHX5XTYV8nQApmEcqaqA3Q1gVHMrXFkXJeV6doDwLWx"
Please delete this `proof` for the same reason as the previous.
```suggestion
```

2023-10-06 19:37 UTC, selfissued commented on index.html
> +    "proofValue": "zqpLMweBrSxMY2xHX5XTYV8nQAJeV6doDwLWxQeVbY4oey5q2pmEcqaqA3Q1gVHMrXFkXM3XKaxup3tmzN4DRFTLV"
And likewise please delete this `proof`.
```suggestion
  }]
```

2023-10-06 19:37 UTC, OR13 commented on index.html
> +          See <a data-cite="VC-DATA-MODEL-2.0#example-a-simple-example-of-a-verifiable-credential"></a> for more details regarding this example.
@selfissued I can't apply your suggestion, these examples are intentionally verbatim from the core specification.

2023-10-06 19:38 UTC, OR13 commented on index.html
> +        See <a data-cite="VC-DATA-MODEL-2.0#example-a-simple-example-of-a-verifiable-presentation"></a> for more details regarding this example.
@selfissued I can't apply your suggestion, these examples are intentionally verbatim from the core specification.

2023-10-06 20:53 UTC, decentralgabe requested changes
agree with @selfissued 's comments

2023-10-09 10:13 UTC, awoie requested changes
I don't think the examples should have a `proof` property. That is confusing to me.

2023-10-13 18:31 UTC, OR13 commented
https://github.com/w3c/vc-data-model/pull/1308

has been merged, I am requesting re-reviews.

2023-10-13 18:34 UTC, selfissued approved these changes
Now that we've merged https://github.com/w3c/vc-data-model/pull/1308 and the corresponding changes have been made here, we're good to go.

2023-10-13 18:36 UTC, merged