Reference Key Discovery section
w3c/vc-jose-cose pull request #200
Opened 2023-12-21 19:00 UTC by selfissued

Fixes #194

2023-12-21 19:03 UTC, decentralgabe approved these changes

2023-12-26 18:56 UTC, TallTed requested changes

2023-12-26 18:56 UTC, TallTed commented on index.html
> +As such, discovery of verification keys is described in Section <a href="#key_discovery"></a>,
```suggestion
Therefore, discovery of verification keys is described in Section <a href="#key_discovery"></a>,
```

2024-01-01 03:01 UTC, selfissued commented on index.html
> +Therefore, discovery of verification keys is described in Section <a href="#key_discovery"></a>,
```suggestion
Therefore, discovery of verification keys is described in <a href="#key_discovery"></a>,
```

2024-01-01 03:09 UTC, merged