change cr date to April 25
w3c/vc-jose-cose pull request #267
Opened 2024-04-19 16:59 UTC by decentralgabe

2024-04-19 17:13 UTC, selfissued approved these changes

2024-04-19 17:39 UTC, iherman requested changes
You should also change the 'end' date for the CR review. It should be set to 25 May

2024-04-19 17:47 UTC, brentzundel approved these changes

2024-04-19 18:20 UTC, decentralgabe commented
@iherman updated

2024-04-20 04:33 UTC, iherman approved these changes
The official publication request has been sent to the W3C webmaster with this version.

2024-04-22 16:06 UTC, merged