add language around not making properties disclosable
w3c/vc-jose-cose pull request #288
Opened 2024-08-06 17:33 UTC by decentralgabe

fix #285 
I will separately need to update the respec plugin to take into account these properties

2024-08-06 17:34 UTC, decentralgabe commented
cc: @goncalo-frade-iohk

2024-08-06 17:44 UTC, TallTed requested changes
Tweak for clarity.

2024-08-06 17:44 UTC, TallTed commented on index.html
> +                <code>credentialSchema</code></a>.
```suggestion
                When securing verifiable credentials with [[SD-JWT]] implementers MUST ensure that
                properties necessary for the validation and verification of a credential are NOT selectively
                disclosable (i.e., such properties MUST be disclosed). These properties include but are not
                limited to <a data-cite="VC-DATA-MODEL-2.0#status"><code>credentialStatus</code></a>
                and <a data-cite="VC-DATA-MODEL-2.0#data-schemas"><code>credentialSchema</code></a>.
```

2024-08-06 17:44 UTC, TallTed commented on index.html
> +                <code>credentialSchema</code></a>.
```suggestion
                When securing verifiable presentations with [[SD-JWT]] implementers MUST ensure that
                properties necessary for the validation and verification of a credential are NOT selectively
                disclosable (i.e., such properties MUST be disclosed). These properties include but are not
                limited to <a data-cite="VC-DATA-MODEL-2.0#status"> <code>credentialStatus</code></a>
                and <a data-cite="VC-DATA-MODEL-2.0#data-schemas"> <code>credentialSchema</code></a>.
```

2024-08-06 20:11 UTC, selfissued approved these changes
LGTM

2024-08-10 13:14 UTC, OR13 approved these changes

2024-08-12 15:33 UTC, decentralgabe commented
Open for over a week. Editorial approval. Changes adopted. Merging.

2024-08-12 15:33 UTC, merged