Use of nbf is NOT RECOMMENDED
w3c/vc-jose-cose pull request #291
Opened 2024-08-18 23:59 UTC by selfissued

Fixes #275

Cc: @sloops77

2024-08-19 16:16 UTC, decentralgabe approved these changes

2024-08-23 17:51 UTC, TallTed requested changes

2024-08-23 17:51 UTC, TallTed commented on index.html
> +		a signature.
`future-date or post-date` are redundant. It's not clear whether the intent was only to discuss dates in the future, or dates in past *or* future.
```suggestion
		as it makes little sense to attempt to assign a future date to
		a signature.
```

2024-08-23 17:51 UTC, TallTed commented on index.html
> +		a signature.
`future-date or post-date` are redundant. It's not clear whether the intent was only to discuss dates in the future, or dates in past *or* future.
```suggestion
		as it makes little sense to attempt to assign a future date to
		a signature.
```

2024-08-26 22:59 UTC, decentralgabe commented
Open for >1 week. Editor's approval. Change requests incorporated. Merging.

2024-08-26 22:59 UTC, merged