Describe encrypting secured credentials and presentations
w3c/vc-jose-cose pull request #293
Opened 2024-08-19 00:58 UTC by selfissued

Fixes #175

2024-08-19 17:33 UTC, decentralgabe approved these changes

2024-08-23 17:53 UTC, TallTed requested changes
Minor grammar

2024-08-23 17:53 UTC, TallTed commented on index.html
> +	      when transmitted over an insecure channel,
```suggestion
	      To encrypt a secured [=verifiable credential=]
	      when transmitting over an insecure channel,
```

2024-08-23 17:53 UTC, TallTed commented on index.html
> +	      when transmitted over an insecure channel,
```suggestion
	      To encrypt a secured [=verifiable presentation=]
	      when transmitting over an insecure channel,
```

2024-08-23 17:53 UTC, TallTed commented on index.html
> +	      when transmitted over an insecure channel,
```suggestion
	      To encrypt a secured [=verifiable credential=]
	      when transmitting over an insecure channel,
```

2024-08-23 17:53 UTC, TallTed commented on index.html
> +	      when transmitted over an insecure channel,
```suggestion
	      To encrypt a secured [=verifiable presentation=]
	      when transmitting over an insecure channel,
```

2024-08-23 17:53 UTC, TallTed commented on index.html
> +	      when transmitted over an insecure channel,
```suggestion
	      To encrypt a secured [=verifiable credential=]
	      when transmitting over an insecure channel,
```

2024-08-23 17:53 UTC, TallTed commented on index.html
> +	      when transmitted over an insecure channel,
```suggestion
	      To encrypt a secured [=verifiable presentation=]
	      when transmitting over an insecure channel,
```

2024-08-26 22:58 UTC, decentralgabe commented
Open for >1 week. Editor's approval. Change requests incorporated. Merging.

2024-08-26 22:58 UTC, merged