Move Conformance section into Introduction
w3c/vc-jose-cose pull request #299
Opened 2024-09-13 19:49 UTC by selfissued

Fixes #284

2024-09-13 20:02 UTC, decentralgabe approved these changes

2024-09-16 17:44 UTC, TallTed requested changes

2024-09-16 17:44 UTC, TallTed commented on index.html
> +            MUST be used to communicate that a JWT Claims Set (a
```suggestion
            JSON Web Tokens, the header parameter setting <code>"alg": "none"</code>,
            MUST be used to communicate that a JWT Claims Set (a
```

2024-09-16 17:44 UTC, TallTed commented on index.html
> +            <code>proof</code> member.
```suggestion
            required to be secured nor integrity protected, nor to contain a
            <code>proof</code> member.
```

2024-09-16 17:44 UTC, TallTed commented on index.html
> +            Verifiable Presentation) contains
This parenthetical note suggests that `a JWT Claims Set` could only be `a Verifiable Credential or a Verifiable Presentation`, but that's not so. If the intent is to say that these sentences only apply to any `JWT Claims Set` that *is* `a Verifiable Credential or a Verifiable Presentation`, they should be reworded, something like this ... and similar changes should be applied throughout the document.
```suggestion
            MUST be used to communicate that a JWT Claims Set that comprises a
            Verifiable Credential or a Verifiable Presentation has no
            integrity protection.
            When a JWT Claims Set that comprises a Verifiable Credential or a
            Verifiable Presentation contains
```

2024-09-16 17:44 UTC, TallTed commented on index.html
> +            have no integrity protection.
```suggestion
            Issuers, Holders, and Verifiers of Verifiable Credentials and/or
            Verifiable Presentations MUST ignore all, and MUST NOT produce any,
            JWT Claims Sets that have no integrity protection.
```

2024-09-16 17:44 UTC, TallTed commented on index.html
> +            MUST NOT be present in any JWT Claims Set.
The existing restriction appears meant to apply to *all* JWT Claims Sets, for which it ought to be part of the JWT RFC, not this separate specification. Thus --
```suggestion
            MUST NOT be present in any JWT Claims Set that comprises a
            Verifiable Credential or a Verifiable Presentation.
```

2024-09-16 17:44 UTC, TallTed commented on index.html
> +        <h2 id="conformance-classes">Conformance Classes</h2>
It seems odd that `<section id="introduction">` is not set as `<section id="introduction" class="normative">... and then the `class="normative"` removed from the sub-sections it contains.

```suggestion
  <section id="conformance" class="normative">
    <section class="normative">
        <h2 id="conformance-classes">Conformance Classes</h2>
```

2024-09-20 20:21 UTC, decentralgabe commented
Changes incorporated. Open for > 1 week. Editorial approval. Merging.

2024-09-20 20:21 UTC, merged