update controller doc examples
w3c/vc-jose-cose pull request #301
Opened 2024-09-17 22:28 UTC by decentralgabe

fix #154

2024-09-17 22:37 UTC, TallTed requested changes
Editorial, for consistency & clarity

2024-09-17 22:37 UTC, TallTed commented on index.html
> +                to establish a cryptographic binding to the Holder in the [=Verifiable Credential=]
```suggestion
                to establish a cryptographic binding to the [=Holder=] in the [=Verifiable Credential=]
```

2024-09-17 22:37 UTC, TallTed commented on index.html
>              required to be secured or integrity protected or to contain a
```suggestion
            required to be secured or integrity protected nor to contain a
```

2024-09-17 22:37 UTC, TallTed commented on index.html
> +            Upon receipt of the [=verifiable credential=] or [=presentation=] secured as a JWT
```suggestion
            Upon receipt of the [=verifiable credential=] or [=verifiable presentation=] secured as a JWT
```

2024-09-17 22:37 UTC, TallTed commented on index.html
> +            Upon receipt of the [=verifiable credential=] or [=presentation=] secured with
```suggestion
            Upon receipt of the [=verifiable credential=] or [=verifiable presentation=] secured with
```

2024-09-17 22:37 UTC, TallTed commented on index.html
> +            Upon receipt of the [=verifiable credential=] or [=presentation=] secured with
```suggestion
            Upon receipt of the [=verifiable credential=] or [=verifiable presentation=] secured with
```

2024-09-17 22:59 UTC, selfissued approved these changes

2024-09-20 20:51 UTC, decentralgabe commented
Updating examples, nothing normative. Editorial approval. Changes and merge conflicts addressed. Merging.

2024-09-20 20:51 UTC, merged