mark sections normative; move algorithms
w3c/vc-jose-cose pull request #302
Opened 2024-09-18 03:25 UTC by decentralgabe

fix #300 

* mark sections as normative, informative
* move algorithms above non-normative section
* combined verification and validation sections under a common 'algorithms' section

2024-09-18 04:05 UTC, selfissued commented
Where can I view the rendered version of this PR?  The usual "Preview" link isn't in evidence.

2024-09-18 04:46 UTC, iherman commented
There seems to be some problem with the background processing that I could not track down. I believe it may be with the "spec generator". That is probably the reason why preview does not appear either.

The (complicated) way around that I found is as follows:

- download the new branch onto the local clone of repository and ask git to make this your current branch
- two possibilities: 
    - if you run a local http server which has access to the repository, then view the index.html file in your browser via localhost
    - otherwise, go to https://labs.w3.org/spec-generator/ and upload the source code there

In theory, one could use the spec generator using https://htmlpreview.github.io/?https://github.com/w3c/vc-jose-cose/blob/fix-300/index.html to render the file, but it returns a (I believe unjustified) but report.

cc @deniak ?

2024-09-18 06:07 UTC, deniak commented
As far as I can tell, spec-generator can process that document just fine, see https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvc-jose-cose%2Fdcfe55993ade74facbd7d39d755e3a89dacefd66%2Findex.html&file=
@tobie, any idea why pr-preview isn't adding the links on that PR? The other PRs seem to work ok.

2024-09-18 06:24 UTC, iherman commented
Hm. Maybe it is a problem with htmlpreview (I must admit I have never used this raw.githubusercontent.com trick).

2024-09-18 18:53 UTC, TallTed commented on index.html
> +<section class="informative" id="introduction">
Non-normative/informative sections cannot contain normative subsections.

Therefore, if, as I believe will be the case when PR-Preview does its thing or when this PR is merged, the Terminology section, which is now meant to be normative, is a sub-section of the Introduction section, then the Introduction section *must* be made normative.
```suggestion
<section class="normative" id="introduction">
```

2024-09-21 03:19 UTC, selfissued requested changes
Please delete all instances of class="normative".  I verified that it doesn't change the output for normative sections, so it's just unnecessary clutter in the source, given that sections are normative by default.

2024-09-22 13:56 UTC, tobie commented
> @tobie, any idea why pr-preview isn't adding the links on that PR? The other PRs seem to work ok.

Not sure what the issue was here. Seems fixed now. LMK if this happens again.

2024-09-26 16:13 UTC, decentralgabe commented on index.html
> +<section class="normative" id="introduction">
```suggestion
<section id="introduction">
```

2024-09-26 16:14 UTC, decentralgabe commented on index.html
> +<section class="normative">
```suggestion
<section>
```

2024-09-26 16:14 UTC, decentralgabe commented on index.html
> +    <section class="normative" id="secure-with-jose">
```suggestion
    <section id="secure-with-jose">
```

2024-09-26 16:16 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:16 UTC, decentralgabe commented on index.html
> +    <section class="normative" id="secure-with-sd-jwt">
```suggestion
    <section id="secure-with-sd-jwt">
```

2024-09-26 16:16 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:17 UTC, decentralgabe commented on index.html
> +    <section class="normative" id="secure-with-cose">
```suggestion
    <section id="secure-with-cose">
```

2024-09-26 16:17 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:17 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:17 UTC, decentralgabe commented on index.html
> +    <section class="normative">
```suggestion
    <section>
```

2024-09-26 16:17 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:17 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:18 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:18 UTC, decentralgabe commented on index.html
> +        <section class="normative">
```suggestion
        <section>
```

2024-09-26 16:22 UTC, decentralgabe commented on index.html
> +    <section class="normative">
```suggestion
    <section class="normative">
```

2024-09-26 16:23 UTC, decentralgabe commented on index.html
>  <section class="normative">
```suggestion
<section>
```

2024-09-26 16:23 UTC, decentralgabe commented on index.html
> +    <section class="normative">
```suggestion
    <section>
```

2024-09-26 16:24 UTC, decentralgabe commented on index.html
> +    <section class="normative">
```suggestion
    <section>
```

2024-09-26 16:44 UTC, selfissued approved these changes

2024-09-26 16:58 UTC, decentralgabe commented
Opened over a week. Changes addressed. Editorial approval. Merging.

2024-09-26 16:58 UTC, merged