add language about selective disclosure considerations
w3c/vc-jose-cose pull request #308
Opened 2024-09-27 22:33 UTC by decentralgabe

fix #285 

examples to be subsequently fixed by https://github.com/w3c/respec-vc/issues/41

2024-09-27 22:33 UTC, decentralgabe commented
@msporny let me know if this addresses your concerns

2024-09-27 22:37 UTC, selfissued approved these changes

2024-09-27 23:10 UTC, TallTed commented on index.html
> +                When securing [=verifiable credentials=] with [[SD-JWT]] implementers MUST ensure that
```suggestion
                When securing [=verifiable presentations=] with [[SD-JWT]] implementers MUST ensure that
```

2024-09-30 18:16 UTC, msporny approved these changes

2024-09-30 19:56 UTC, dlongley approved these changes
Approving, though in my opinion, there could be more nuance here. Some of these properties are clearly required for consistent semantics (e.g., `@context`, `type`), others are really "up to the issuer". If the issuer doesn't mind a holder presenting without credential status, for example, I don't think that issuer MUST include it as mandatory. Who knows what the credential status is for here (e.g., it may not be for revocation).

So I don't think this language has to be as strict as it is, but since I'm not volunteering to come up with alternative language either, I approve as-is.

2024-09-30 20:31 UTC, TallTed requested changes
Does this do what you were thinking appropriate, @dlongley?

2024-09-30 20:31 UTC, TallTed commented on index.html
>                  disclosable (i.e., such properties MUST be disclosed). These properties include but are not
```suggestion
                When securing [=verifiable credentials=] with [[SD-JWT]], implementers SHOULD ensure that
                properties necessary for the validation and verification of a credential are NOT selectively
                disclosable (i.e., such properties SHOULD be disclosed). These properties can include but are not
```

2024-09-30 20:31 UTC, TallTed commented on index.html
> +                and <a data-cite="VC-DATA-MODEL-2.0#integrity-of-related-resources"><code>relatedResource</code></a>.
```suggestion
                limited to <a data-cite="VC-DATA-MODEL-2.0#contexts"><code>@context</code></a>,
                <a data-cite="VC-DATA-MODEL-2.0#types"><code>type</code></a>,
                <a data-cite="VC-DATA-MODEL-2.0#status"><code>credentialStatus</code></a>,
                <a data-cite="VC-DATA-MODEL-2.0#data-schemas"><code>credentialSchema</code></a>,
                and <a data-cite="VC-DATA-MODEL-2.0#integrity-of-related-resources"><code>relatedResource</code></a>.
```

2024-09-30 20:31 UTC, TallTed commented on index.html
>                  disclosable (i.e., such properties MUST be disclosed). These properties include but are not
```suggestion
                When securing [=verifiable presentations=] with [[SD-JWT]] implementers SHOULD ensure that
                properties necessary for the validation and verification of a credential are NOT selectively
                disclosable (i.e., such properties SHOULD be disclosed). These properties can include but are not
```

2024-09-30 20:31 UTC, TallTed commented on index.html
> +                and <a data-cite="VC-DATA-MODEL-2.0#integrity-of-related-resources"><code>relatedResource</code></a>.
```suggestion
                limited to <a data-cite="VC-DATA-MODEL-2.0#contexts"><code>@context</code></a>,
                <a data-cite="VC-DATA-MODEL-2.0#types"><code>type</code></a>,
                <a data-cite="VC-DATA-MODEL-2.0#status"><code>credentialStatus</code></a>,
                <a data-cite="VC-DATA-MODEL-2.0#data-schemas"><code>credentialSchema</code></a>,
                and <a data-cite="VC-DATA-MODEL-2.0#integrity-of-related-resources"><code>relatedResource</code></a>.
```

2024-09-30 22:10 UTC, dlongley commented
@TallTed, yes, I can also accept SHOULD and leave the nuance to the issuer/implementer.

2024-10-04 19:36 UTC, decentralgabe commented
Open for over a week. Changes accepted. Editorial approval. Merging!

2024-10-04 19:36 UTC, merged