Add language from resolution about differentiating using cty
w3c/vc-jose-cose pull request #314
Opened 2024-10-09 22:35 UTC by brentzundel

Some of the language from the WG's resolution is not yet captured in the specification, in particular:
```
We will note in particular that the cty property is the point of differentiation
for others that may wish to use identical media types. This group intends to
use application/vc and application/vp as the cty values.
```
This PR adds that language to the specification, and if merged may address issue #313

2024-10-09 22:38 UTC, decentralgabe approved these changes

2024-10-10 00:05 UTC, selfissued commented on index.html
> +                media type.
```suggestion
                The <code>cty</code> header parameter value can be used to differentiate between secured content of different types when using <code>vc+jwt</code>.
```

2024-10-10 00:06 UTC, selfissued commented on index.html
> +                media type.
```suggestion
                The <code>cty</code> header parameter value can be used to differentiate between secured content of different types when using <code>vp+jwt</code>.
```

2024-10-10 00:06 UTC, selfissued commented on index.html
> +                identical media type.
```suggestion
                The <code>cty</code> header parameter value can be used to differentiate between secured content of different types when using <code>vc+sd-jwt</code>.
```

2024-10-10 00:07 UTC, selfissued commented on index.html
> +                identical media type.
```suggestion
                The <code>cty</code> header parameter value can be used to differentiate between secured content of different types when using <code>vp+sd-jwt</code>.
```

2024-10-10 00:09 UTC, selfissued commented on index.html
> +                wish to use an identical media type.
```suggestion
                The <code>content type (3)</code> header parameter value can be used to differentiate between secured content of different types when using <code>application/vc+cose</code>.
```

2024-10-10 00:09 UTC, selfissued commented on index.html
> +                wish to use an identical media type.
```suggestion
                The <code>content type (3)</code> header parameter value can be used to differentiate between secured content of different types when using <code>application/vp+cose</code>.
```

2024-10-10 00:10 UTC, selfissued requested changes
Please apply my suggested changes to tighten the wording.

2024-10-10 06:11 UTC, iherman approved these changes

2024-10-10 14:42 UTC, msporny approved these changes

2024-10-10 14:59 UTC, TallTed commented on index.html
> +                The <code>cty</code> header parameter value can be used to differentiate between secured content of different types when using <code>vc+jwt</code>.
I think this language needs a bit more work (to be applied to all occurences). I do not yet have a suggestion, but I expect to figure it out today.

2024-10-10 22:33 UTC, decentralgabe commented on index.html
>              SHOULD be <code>application/vc</code>.
```suggestion
            When present, the <code>content type (3)</code> header parameter
            SHOULD be <code>application/vc</code>.
            The <code>content type (3)</code> header parameter value can be used
            to differentiate between secured content of different types when using
            <code>application/vc+cose</code>.
```

2024-10-10 22:34 UTC, decentralgabe commented on index.html
> +            See <a data-cite="RFC9052#section-3.1">Common COSE Header Parameters</a>
```suggestion
            The <code>typ</code> header parameter SHOULD be <code>application/vp+cose</code>.
            When present, the <code>content type (3)</code> header parameter SHOULD be   <code>application/vp</code>.
            The <code>content type (3)</code> header parameter value can be used to differentiate
            between secured content of different types when using <code>application/vp+cose</code>.
            See <a data-cite="RFC9052#section-3.1">Common COSE Header Parameters</a>
```

2024-10-10 22:34 UTC, decentralgabe commented on index.html
> +            When present, the <code>content type (3)</code> header parameter SHOULD be   <code>application/vp</code>.
```suggestion
            When present, the <code>content type (3)</code> header parameter SHOULD be <code>application/vp</code>.
```

2024-10-16 12:44 UTC, OR13 approved these changes

2024-10-16 21:02 UTC, decentralgabe commented
editorial approval; open >1 week; changes accepted; merging.

2024-10-16 21:02 UTC, merged